#!/bin/bash
#Count and list system services
echo " ";
echo -n "SERVICES COUNT:";
sudo systemctl | awk '{print$1}'|grep -i "service"|wc|awk '{print$1}'
echo "";
sudo systemctl | awk '{print$1}' | grep -i "service\|running"|nl|more
